-- CREAMOS LOS ROLES

CREATE ROLE ROL_ADMIN_SISTEMA;
CREATE ROLE ROL_USUARIO;
CREATE ROLE ROL_GESTOR_CUENTAS;
CREATE ROLE ROL_PLANIFICADOR_SERVICIOS;

-- * PERMISOS ADMIN_SISTEMA
GRANT ADMINISTER KEY MANAGEMENT TO ROL_ADMIN_SISTEMA;
GRANT EXECUTE ON DBMS_RLS TO ROL_ADMIN_SISTEMA;

-- OTORGAMOS PERMISOS COMPLETOS SOBRE LAS TABLAS AL ROL_ADMIN_SISTEMA
GRANT ALL ON Activo TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Atributo TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Atributos_Producto TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Categoria TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Categoria_Activos TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Cuenta TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Plan TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Producto TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Rel_Activ_CategAct TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Rel_Prod_Activ TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Rel_Prod_Categ TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Relacionado TO ROL_ADMIN_SISTEMA;
GRANT ALL ON Usuario TO ROL_ADMIN_SISTEMA;

-- OTORGAMOS PERMISOS PARA CREAR, MODIFICAR Y ELIMINAR CUENTAS, USUARIOS, PRODUCTOS, ACTIVOS Y PLANES
GRANT CREATE ANY TABLE TO ROL_ADMIN_SISTEMA;
GRANT ALTER ANY TABLE TO ROL_ADMIN_SISTEMA;
GRANT DROP ANY TABLE TO ROL_ADMIN_SISTEMA;

-- * PERMISOS USUARIO

-- VER Y MODIFICAR SU PROPIA INFORMACION DE USUARIO
CREATE OR REPLACE VIEW V_USUARIO_ESTANDAR AS
SELECT *
FROM USUARIO
WHERE NOMBREUSUARIO = USER;

GRANRT SELECT, UPDATE ON V_USUARIO_ESTANDAR TO ROL_USUARIO;

-- ACCEDER A PRODUCTOS, ACTIVOS Y ATRIBUTOS DE SU PROPIA CUENTA Y DAR DE ALTA PRODUCTOS, ACTIVOS Y ATRIBUTOS
CREATE OR REPLACE VIEW V_USUARIO_PRODUCTO AS
SELECT * FROM PRODUCTO WHERE CUENTA_ID = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER)
WITH CHECK OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON V_USUARIO_PRODUCTO TO ROL_USUARIO;
CREATE OR REPLACE SYNONYM PRODUCTO FOR PLYTIX.V_USUARIO_PRODUCTO;


CREATE OR REPLACE VIEW V_USUARIO_ACTIVO AS
SELECT * FROM ACTIVO WHERE CUENTA_ID = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER)
WITH CHECK OPTION;

GRANT SELECT, INSERT ON V_USUARIO_ACTIVO TO ROL_USUARIO;
CREATE OR REPLACE SYNONYM ACTIVO FOR PLYTIX.V_USUARIO_ACTIVO;

CREATE OR REPLACE VIEW V_USUARIO_ATRIBUTO AS
SELECT * FROM ATRIBUTO WHERE CUENTA_ID = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER)
WITH CHECK OPTION;

GRANT SELECT, INSERT ON V_USUARIO_ATRIBUTO TO ROL_USUARIO;
CREATE OR REPLACE SYNONYM ATRIBUTO FOR PLYTIX.V_USUARIO_ATRIBUTO;

-- * PERMISOS GESTOR_CUENTAS

-- ACCEDE Y ADMINISTRA LA TABLA CUENTA, NO TIENE ACCESO A DATOS SENSIBLES DE USUARIOS
CREATE OR REPLACE VIEW V_GESTOR_CUENTAS AS
SELECT ID, NOMBRE, DIRECCIONFISCAL, NIF, FECHAALTA, PLAN_ID, USUARIO_CUENTA_ID, USUARIO_ID FROM CUENTA;

GRANT SELECT, INSERT, UPDATE, DELETE ON V_GESTOR_CUENTAS TO ROL_GESTOR_CUENTAS;

-- * PERMISOS PLANIFICADOR_SERVICIOS

-- ADMINISTRA LA TABLA PLAN Y SUS RELACIONES (PRODUCTOS, ACTIVOS, CATEGORIASPRODUCTOS Y CATEGORIASACTIVOS)
GRANT SELECT, INSERT, UPDATE, DELETE ON PLAN TO PLANIFICADOR_SERVICIOS;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCTO TO PLANIFICADOR_SERVICIOS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACTIVO TO PLANIFICADOR_SERVICIOS;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIA_PRODUCTO TO PLANIFICADOR_SERVICIOS;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIA_ACTIVO TO PLANIFICADOR_SERVICIOS;


-- RF1. Gestión de los Productos, Categorías y Activos

-- 1.1. Otorgar los permisos al Usuario Estándar para hacer CRUD (Create, read, Update, Delete) de la tabla Producto
-- YA LO HEMOS HECHO ANTES

-- 1.2. Cambio de público a privado o viceversa de los productos

ALTER TABLE PRODUCTO
ADD PUBLICO CHAR(1) DEFAULT 'S' CHECK (PUBLICO IN ('S', 'N'));

-- 1.3. Crear una vista V_PRODUCTO_PUBLICO para productos públicos
CREATE OR REPLACE VIEW V_PRODUCTO_PUBLICO AS
SELECT * FROM PRODUCTO WHERE PUBLICO = 'S'
WITH CHECK OPTION;

GRANT SELECT ON V_PRODUCTO_PUBLICO TO ROL_USUARIO;
CREATE OR REPLACE SYNONYM PRODUCTO_PUBLICO FOR PLYTIX.V_PRODUCTO_PUBLICO;

-- 1.4. Otorgar los permisos al Usuario estándar para hacer CRUD (Create, read, Update, Delete) de la tabla Activo y la relación de Activos y Categorías de activos. 

CREATE OR REPLACE VIEW V_ACTIVO_REL_ACTIVO_CATEGORIA AS
SELECT *
FROM Rel_Activ_CategAct WHERE Activo_Cuenta_Id = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER)
WITH CHECK OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ACTIVO_REL_ACTIVO_CATEGORIA TO ROL_USUARIO;
CREATE OR REPLACE SYNONYM REL_ACTIVO_CATEGORIA FOR PLYTIX.V_ACTIVO_REL_ACTIVO_CATEGORIA;

-- NO SE SI HABRIA QUE MODIFICAR EL TRIGGER DE PRODUCTOS

-- 1.5. Otorgar los permisos al Usuario estándar para hacer CRUD (Create, read, Update, Delete) de la tabla Categoría y la relación productos y Categorías

CREATE OR REPLACE VIEW V_CATEGORIA AS
SELECT * FROM CATEGORIA WHERE CUENTA_ID = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER)
WITH CHECK OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON V_CATEGORIA TO ROL_USUARIO;
CREATE OR REPLACE SYNONYM CATEGORIA FOR PLYTIX.V_CATEGORIA;

CREATE OR REPLACE VIEW V_REL_PRODUCTO_CATEGORIA AS
SELECT * FROM Rel_Prod_Categ WHERE Producto_Cuenta_Id = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER)

-- 1.6. Otorgar los permisos al Usuario estándar para hacer CRUD (Create, read, Update, Delete) de la tabla Relacionado.

CREATE OR REPLACE VIEW V_RELACIONADO AS
SELECT * FROM RELACIONADO WHERE CUENTA_ID = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER)
WITH CHECK OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON V_RELACIONADO TO ROL_USUARIO;
CREATE OR REPLACE SYNONYM RELACIONADO FOR PLYTIX.V_RELACIONADO;

-- 1.7. Otorgar los permisos al Usuario estándar para hacer CRUD (Create, read, Update, Delete) de la tabla Atributo y la relación de Atributos y Productos.

CREATE OR REPLACE VIEW V_ATRIBUTO_PRODUCTO AS
SELECT * FROM ATRIBUTO_PRODUCTO WHERE PRODUCTO_CUENTA_ID = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER)
WITH CHECK OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ATRIBUTO_PRODUCTO TO ROL_USUARIO;
CREATE OR REPLACE SYNONYM ATRIBUTO_PRODUCTO FOR PLYTIX.V_ATRIBUTO_PRODUCTO;

-- 2. RF3. Gestión de las cuentas.

-- 2.1. Otorgar los permisos al Gestor de cuentas para hacer CRUD (Create, read, Update, Delete) de la tabla Cuenta

-- YA LO HEMOS HECHO ANTES

-- 2.2. Otorgarle los permisos para acceder a los atributos de usuario necesarios.

CREATE OR REPLACE VIEW V_USUARIO_GESTOR_CUENTAS AS
SELECT ID, NOMBREUSUARIO, NombreCompleto, CorreoElectronico, Telefono FROM USUARIO
WHERE ID IN (SELECT USUARIO_ID FROM CUENTA WHERE USUARIO_CUENTA_ID = (SELECT CUENTA_ID FROM USUARIO WHERE NOMBREUSUARIO = USER))
WITH CHECK OPTION;

-- 3. RF4. Gestión de los planes.

-- 3.1. Otorgar los permisos al Planificador de servicios para hacer CRUD (Create, read, Update, Delete) de la tabla Plan
-- YA LO HEMOS HECHO ANTES