CREATE OR REPLACE FUNCTION  F_OBTENER_PLAN_CUENTA(p_cuenta_id IN CUENTA.ID%TYPE) RETURN PLAN%ROWTYPE
AS
BEGIN

    NULL;
-- EXCEPTION
END;
/

SELECT F_OBTENER_PLAN_CUENTA(Cuenta_Id) FROM DUAL;

CREATE OR REPLACE PACKAGE PKG_ADMIN_PRODUCTOS AS

    EXCEPTION_PLAN_NO_ASIGNADO EXCEPTION; -- Excepción personalizada para el caso de que no haya un plan asignado a la cuenta

    FUNCTION F_OBTENER_PLAN_CUENTA(p_cuenta_id IN CUENTA.ID%TYPE) RETURN PLAN%ROWTYPE;

    FUNCTION F_CONTAR_PRODUCTOS_CUENTA(p_cuenta_id IN CUENTA.ID%TYPE) RETURN NUMBER;

    FUNCTION F_VALIDAR_ATRIBUTOS_PRODUCTO(p_producto_gtin IN PRODUCTO.GTIN%TYPE, 
    p_cuenta_id IN PRODUCTO.CUENTA_ID%TYPE) RETURN BOOLEAN;

    FUNCTION F_NUM_CATEGORIAS_CUENTA(p_cuenta_id IN CUENTA.ID%TYPE) RETURN NUMBER;

    PROCEDURE  P_ACTUALIZAR_NOMBRE_PRODUCTO(p_producto_gtin IN PRODUCTO.GTIN%TYPE, 
    p_cuenta_id IN PRODUCTO.CUENTA_ID%TYPE, p_nuevo_nombre IN 
    PRODUCTO.NOMBRE%TYPE);

END;
/
-- UNA VEZ QUE TENGO LA CABECERA, HAGO CLICK DERECHO EN EL PAQUETE Y LE DOY A GENERAR CUERPO Y ASÍ ME AHORRO DE ESCRIBIRLO A MANO

CREATE TABLE TRAZA (FECHA TIMESTAMP, USUARIO VARCHAR2(30), MODULO VARCHAR2(30), MENSAJE VARCHAR2(500)); -- TRAZA DE ERRORES

CREATE OR REPLACE PACKAGE BODY PKG_ADMIN_PRODUCTOS AS
    -- Esta función no se puede usar fuera de este paquete
    FUNCTION X(A INTENGER) RETURN INTENGER IS
    BEGIN
        RETURN A + 1;
    END X;

    FUNCTION F_OBTENER_PLAN_CUENTA(p_cuenta_id IN CUENTA.ID%TYPE) 
        RETURN PLAN%ROWTYPE AS
        v_plan PLAN%ROWTYPE;
    BEGIN

        SELECT COUNT(*) INTO V_CUENTA FROM CUENTA WHERE ID = p_cuenta_id FOR UPDATE;
        IF V_CUENTA = 0 THEN
            RAISE NO_DATA_EXCEPTION; -- Lanza la excepción personalizada si no hay un plan asignado
        END IF;
        
        SELECT * INTO V_CUENTA FROM CUENTA WHERE ID = p_cuenta_id;

        IF V_CUENTA.PLAN IS NULL THEN
            RAISE EXCEPTION_PLAN_NO_ASIGNADO; -- Lanza la excepción personalizada si no hay un plan asignado
        END IF;

        BEGIN
            SELECT * INTO v_plan FROM PLAN WHERE ID = (SELECT PLAN FROM CUENTA WHERE ID = p_cuenta_id);
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE EXCEPTION_PLAN_NO_ASIGNADO; -- Lanza la excepción personalizada si no hay un plan asignado
        END;


        -- SELECT COUNT(*) INTO V_CUENTA FROM PLAN WHERE ID = (SELECT PLAN FROM CUENTA WHERE ID = p_cuenta_id);
        -- IF V_CUENTA = 0 THEN
        --     RAISE EXCEPTION_PLAN_NO_ASIGNADO; -- Lanza la excepción personalizada si no hay un plan asignado
        -- END IF;

        RETURN v_plan;
    EXCEPTION
        WHEN OTHERS THEN
            INSERT INTO TRAZA VALUES(SYSDATE, USER, $$PLQSQL_UNIT, SQLCODE||' '||(SQL_ERRM, 1, 500));
    END F_OBTENER_PLAN_CUENTA;
    -- INCONVENIENTE: NO TOLERA ERRORES (SI EL PLAN NO EXISTE O EL PLAN NO EXISTE)
END;
/